[package]
name = "libp2p-pathranker"
version = "0.1.0"
edition = "2024"

[features]
default = []

[dependencies]
libp2p = { version = "0.56.0", features = ["request-response", "tokio", "cbor"] }
serde = { version = "1.0.229", features = ["derive"] }
rand = { workspace = true }
lru = "0.18"
tracing.workspace = true
