[package]
name = "openwire_core"
version = "0.1.0"
edition = "2024"
[features]

default = ["mem_dht", "sqlite_history_storage", "pathranker"]
sqlite_history_storage = []
mem_dht = ["dashmap"]
redb_dht = ["redb"]
pathranker = ["libp2p-pathranker"]
[dependencies]
thiserror = "2"
libp2p = { workspace = true }
anyhow = "1.0.104"
futures = "0.3.33"
rootcell = { workspace = true }
postcard = { version = "1.1", features = ["alloc"] }
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10"
tracing-subscriber = { version = "0.3.23", features = ["fmt", "env-filter"] }
sqlx = { version = "0.9.0", features = ["sqlite", "runtime-tokio", "macros"] }
tokio = { workspace = true }
tracing-appender = "0.2.5"
tracing = { workspace = true }
aes-gcm = "0.11.0"

aws-lc-rs = { version = "1.17", features = ["unstable", "prebuilt-nasm"] }


hex = "0.4.3"
blake3 = "1.8.5"
rand = "0.10.2"
lru = "0.18.1"

dashmap = { version = "6", optional = true }
redb = { version = "4.1.0", optional = true }
zeroize = { version = "1.9.0", features = ["zeroize_derive"] }
async-compression = { version = "0.4.43", features = ["futures-io", "zstd"] }
tokio-util = { version = "0.7", features = ["compat", "rt"] }
async-trait = "0.1.91"
vstd = "0.0.0-2026-07-27-0206"
tokio-tungstenite = "0.24"
libp2p-pathranker = { path = "../libp2p-pathranker", optional = true }
[dev-dependencies]
serde_json = "1"

[package.metadata.docs.rs]
#no-deps = true
