[package]
name = "openwire_core"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2"
libp2p = { workspace = true }
anyhow = "1.0.103"
futures = "0.3.32"
quinn = "0.11.11"
rootcell = { workspace = true }
postcard = { version = "1.1", features = ["alloc"] }
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.11"
tracing-subscriber = { version = "0.3.23", features = ["fmt", "env-filter"] }
sqlx = { version = "0.9.0", features = ["sqlite", "runtime-tokio", "macros"] }
tokio = { workspace = true }
tracing-appender = "0.2.5"
tracing = { workspace = true }
aes-gcm = "0.11.0"

aws-lc-rs = { version = "1.17", features = ["unstable", "prebuilt-nasm"] }


hex = "0.4.3"
blake3 = "1.8.5"
rand = "0.10.2"
lru = "0.18.0"

dashmap = "6"
redb = "4.1.0"
zeroize = { version = "1.9.0", features = ["zeroize_derive"] }
async-compression = { version = "0.4.42", features = ["futures-io", "zstd"] }
tokio-util = { version = "0.7", features = ["compat", "rt"] }
keyring = { version = "4.1.2" }
async-trait = "0.1.89"
vstd = "0.0.0-2026-06-14-0213"

[dev-dependencies]
serde_json = "1"

[package.metadata.docs.rs]
#no-deps = true
