[workspace]
members = ["openwire_core", "rootcell", "openwire_cli", "openwire/src-tauri"]
resolver = "3"

[workspace.dependencies]
rootcell = { path = "rootcell" }
openwire_core = { path = "openwire_core" }
tokio = { version = "1.52.3", features = ["full"] }
libp2p = { version = "0.56.0", features = [
    "autonat",
    "dns",
    "tokio",
    "cbor",
    "request-response",
    "mdns",
    "relay",
    "identify",
    "ping",
    "dcutr",
    "macros",
    "quic",
    "kad",
    "secp256k1",
    "ed25519",
    "tcp",
    "noise",
    "yamux",
    "memory-connection-limits",
] }
tracing = "0.1.44"
[profile.dev]
incremental = true
lto = false

[profile.release]
codegen-units = 1
lto = "thin"
opt-level = 3
panic = "abort"
strip = true
debug = false
debug-assertions = false
overflow-checks = true
