[workspace]
members = [
    "openwire_core",
    "rootcell",
    "openwire_cli",
    "openwire/src-tauri",
    "libp2p-pathranker",
    "openwire_server/common",
    "openwire_server/server_cli",
]
resolver = "3"

[workspace.dependencies]
rootcell = { path = "rootcell" }
openwire_core = { path = "openwire_core" }
tokio = { version = "1.53.1", features = [
    "rt-multi-thread",
    "macros",
    "sync",
    "net",
    "io-util",
    "io-std",
    "time",
    "process",
    "signal",
] }
libp2p = { version = "0.56.0", features = [
    "autonat",
    "dns",
    "tokio",
    "cbor",
    "request-response",
    "mdns",
    "relay",
    "identify",
    "ping",
    "dcutr",
    "macros",
    "quic",
    "kad",
    "ed25519",
    "tcp",
    "noise",
    "yamux",
    "memory-connection-limits",
    "websocket",
    "upnp",
] }
tracing = "0.1.44"
rand = "0.10"
[patch.crates-io]
libp2p-mdns = { path = "patches/libp2p-mdns" }
libp2p-relay = { path = "patches/libp2p-relay" }
libp2p-request-response = { path = "patches/libp2p-request-response" }

[profile.dev]
incremental = true
lto = false
#opt-level = 0
#codegen-units = 256
[profile.release]
opt-level = "s"
codegen-units = 1
lto = "thin"
panic = "abort"
strip = true
debug = false
debug-assertions = false
overflow-checks = true
