#[source.crates-io]
#replace-with = "ustc"

[source.ustc]
registry = "sparse+https://mirrors.ustc.edu.cn/crates.io-index/"

[source.tuna]
registry = "sparse+https://mirrors.tuna.tsinghua.edu.cn/crates.io-index/"

[source.sjtu]
registry = "sparse+https://mirrors.sjtug.sjtu.edu.cn/crates.io-index/"

[net]
[env]
AWS_LC_SYS_PREBUILT_NASM = "1"
[build]
#[target.'cfg(target_os = "linux")']
#linker = "clang"
#rustflags = ["-C", "link-arg=-fuse-ld=lld"]
