[package]
name = "chat_core"
version = "0.1.0"
edition = "2024"

[dependencies]
libp2p = { version = "0.56.0", features = [
    "dns",
    "tokio",
    "cbor",
    "request-response",
    "mdns",
    "relay",
    "identify",
    "ping",
    "dcutr",
    "noise",
    "macros",
    "tcp",
    "yamux",
    "quic",
    "kad",
    "rsa",
    "secp256k1",
    "ed25519",
] }
anyhow = "1.0.102"
futures = "0.3.32"
quinn = "0.11.9"
rootcell = { workspace = true }
postcard = { version = "1.1", features = ["alloc"] }
serde = { version = "1.0", features = ["derive"] }
tracing-subscriber = { version = "0.3.23", features = ["fmt", "env-filter"] }
sqlx = { version = "0.8.6", features = ["sqlite", "runtime-tokio", "macros"] }
tokio = { workspace = true }
tracing-appender = "0.2.4"
tracing = { workspace = true }
aes-gcm = "0.10.3"


keyring = "3.6.3"
snap = "1.1.1"
blake3 = "1.8.3"
rand = "0.10.0"
lru = "0.16.3"
sled = "0.34.7"
redb = "3.1.1"

[package.metadata.docs.rs]
#no-deps = true
