[package]
name = "chat_core"
version = "0.1.0"
edition = "2024"

[dependencies]
libp2p = { workspace = true }
anyhow = "1.0.102"
futures = "0.3.32"
quinn = "0.11.9"
rootcell = { workspace = true }
postcard = { version = "1.1", features = ["alloc"] }
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.11"
tracing-subscriber = { version = "0.3.23", features = ["fmt", "env-filter"] }
sqlx = { version = "0.8.6", features = ["sqlite", "runtime-tokio", "macros"] }
tokio = { workspace = true }
tracing-appender = "0.2.4"
tracing = { workspace = true }
aes-gcm = "0.10.3"
x25519-dalek = { version = "2.0", features = ["static_secrets"] }
pqcrypto-kyber = "0.8.1"


keyring = { version = "3.6.3", features = [
    "apple-native",
    "windows-native",
    "sync-secret-service",
] }
hex = "0.4.3"
snap = "1.1.1"
blake3 = "1.8.4"
rand = "0.10.1"
lru = "0.16.3"
sled = "0.34.7"
redb = "4.0.0"
pqcrypto-traits = "0.3.5"

[package.metadata.docs.rs]
#no-deps = true