name: "publish-tauri"
on:
  workflow_dispatch:
  push:
    branches:
      - release
      - nightly

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest"
            args: "--target aarch64-apple-darwin"
          - platform: "macos-latest"
            args: "--target x86_64-apple-darwin"
          - platform: "ubuntu-22.04"
            args: ""
          - platform: "ubuntu-22.04-arm"
            args: ""
          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v6

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      - name: install dependencies (ubuntu arm only)
        if: matrix.platform == 'ubuntu-22.04-arm'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev:arm64 libwebkit2gtk-4.1-dev:arm64 libappindicator3-dev:arm64 librsvg2-dev:arm64 patchelf pkg-config xdg-utils
      - name: setup node
        uses: actions/setup-node@v6
        with:
          cache-dependency-path: "./chat_tauri/package-lock.json"
          node-version: lts/*
          cache: "npm"

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' &&
            'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      # Rust cache 必须在 workspace 根目录执行，才能正确缓存所有 workspace 成员
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: |
            . -> openwire/src-tauri/target
            openwire_core
            rootcell
            openwire_cli
          cache-targets: "true"
          cache-all-crates: "true"
          cache-bin: "true"
          cache-on-failure: "true"

      - name: install frontend dependencies
        working-directory: ./openwire
        run: npm install
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: "./openwire/src-tauri"
          tagName: "app-v__VERSION__" # the action automatically replaces \_\_VERSION\_\_ with the app version.
          releaseName: "App v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
